# Organizing a travel guide for museums around the world.
world_museums = {
    "european_museums": {
        "Germany": ["German Historical Museum", "Academy of Sciences"],
        "France": ["Louvre Museum", "Orsay Museum"],
        "Italy": ["Uffizi Gallery", "Vatican Museums"],
        "Spain": ["Prado Museum", "Reina Sofia Museum"],
        "United Kingdom": ["National Museum", "Science Museum"],
        "Russia": ["Moscow State Historical and Cultural Museum", "Russian Museum"],
        "Poland": ["National Museum of History and Art", "Museum of Modern Art"],
        "Ukraine": ["National Museum of History and Art", "Museum of Modern Art"],
        "Belgium": ["Museum of Antiquities", "Museum of Fine Arts"],
        "Netherlands": ["Museum of Modern Art", "Stedelijk Museum"],
        "Austria": ["Museum of Modern Art", "Museum of Fine Arts"],
        "Greece": ["Acropolis Museum", "Museum of Modern Art"],
        "Portugal": ["Museum of Modern Art", "Museum of Fine Arts"],
        "Sweden": ["Museum of Modern Art", "Museum of Fine Arts"],
        "Switzerland": ["Museum of Modern Art", "Museum of Fine Arts"],
        "Denmark": ["Museum of Modern Art", "Museum of Fine Arts"],
        "Norway": ["Museum of Modern Art", "Museum of Fine Arts"],
        "Finland": ["Museum of Modern Art", "Museum of Fine Arts"],
        "Estonia": ["Museum of Modern Art", "Museum of Fine Arts"],
        "Latvia": ["Museum of Modern Art", "Museum of Fine Arts"],
        "Lithuania": ["Museum of Modern Art", "Museum of Fine Arts"],
        "Luxembourg": ["Museum of Modern Art", "Museum of Fine Arts"],
        "Monaco": ["Museum of Modern Art", "Museum of Fine Arts"],
        "Malta": ["Museum of Modern Art", "Museum of Fine Arts"],
        "Ireland": ["Museum of Modern Art", "Museum of Fine Arts"],
    },
    "asian_museums": {
        "Thailand": ["Wat Phra Kaew", "Angkor Wat"],
        "Singapore": ["Singapore Zoo", "Merlion Park"],
        "Japan": ["Tokyo Museum of Art", "Kyoto Temple"],
        "South Korea": ["Gwangju Museum of Art", "Seoul Museum of Art"],
        "China": ["Peking Museum", "Shanghai Museum"],
        "India": ["Taj Mahal", "Golden Temple"],
        "Indonesia": ["Bali Museum", "Raja Ampat Museum"],
        "Philippines": ["Philippine Museum of Art", "Philippine Museum of Science"],
        "Vietnam": ["Ho Chi Minh City Museum", "Ho Chi Minh City Museum"],
        "Myanmar": ["Myanmar National Museum", "Myanmar National Museum"],
        "Cambodia": ["Angkor Wat", "Angkor Wat"],
        "Laos": ["Vatican Museums", "Vatican Museums"],
        "Malaysia": ["Malaysia Museum", "Malaysia Museum"],
        "Australia": ["Sydney Opera House", "Sydney Opera House"],
        "New Zealand": ["Wellington Museum", "Wellington Museum"],
        "Papua New Guinea": ["Port Moresby Museum", "Port Moresby Museum"],
        "Fiji": ["Museum of Fine Arts", "Museum of Fine Arts"],
        "Solomon Islands": ["Museum of Fine Arts", "Museum of Fine Arts"],
        "Vanuatu": ["Museum of Fine Arts", "Museum of Fine Arts"],
        "New Caledonia": ["Museum of Fine Arts", "Museum of Fine Arts"],
        "French Polynesia": ["Museum of Fine Arts", "Museum of Fine Arts"],
        "Samoa": ["Museum of Fine Arts", "Museum of Fine Arts"],
        "Tonga": ["Museum of Fine Arts", "Museum of Fine Arts"],
        "Cook Islands": ["Museum of Fine Arts", "Museum of Fine Arts"],
    },
    "south_pacific_museums": {
        "New Zealand": ["Wellington Museum", "Auckland Museum"],
        "Australia": ["Sydney Opera House", "Uluru (Aursol)"],
        "Papua New Guinea": ["Port Moresby Museum", "Trawling Museum"],
        "Fiji": ["Museum of Fine Arts", "Museum of Fine Arts"],
        "Solomon Islands": ["Museum of Fine Arts", "Museum of Fine Arts"],
        "Vanuatu": ["Museum of Fine Arts", "Museum of Fine Arts"],
        "New Caledonia": ["Museum of Fine Arts", "Museum of Fine Arts"],
        "French Polynesia": ["Museum of Fine Arts", "Museum of Fine Arts"],
        "Samoa": ["Museum of Fine Arts", "Museum of Fine Arts"],
        "Tonga": ["Museum of Fine Arts", "Museum of Fine Arts"],
        "Cook Islands": ["Museum of Fine Arts", "Museum of Fine Arts"],
    },
    "african_museums": {
        "Egypt": ["Great Pyramid of Giza", "Sphinx's Temple"],
        "Kenya": ["Nairobi Museum", "Mashinani Museum"],
        "Tanzania": ["Mashinani Museum", "Mashinani Museum"],
        "Zimbabwe": ["Victoria Falls", "Mashinani Museum"],
        "Botswana": ["Mashinani Museum", "Mashinani Museum"],
        "Lesotho": ["Mashinani Museum", "Mashinani Museum"],
        "Zambia": ["Mashinani Museum", "Mashinani Museum"],
        "Malawi": ["Mashinani Museum", "Mashinani Museum"],
        "Mozambique": ["Mashinani Museum", "Mashinani Museum"],
        "South Africa": ["Mashinani Museum", "Mashinani Museum"],
        "Namibia": ["Mashinani Museum", "Mashinani Museum"],
        "Angola": ["Mashinani Museum", "Mashinani Museum"],
        "Botswana": ["Mashinani Museum", "Mashinani Museum"],

    },
    "north_american_museums": {
        "Canada": ["CN Tower", "Toronto Island"],
        "United States": ["National Museum of America", "Whitman Museum"],
        "Mexico": ["Temple of the Sacred Heart", "Chichen Itza"],
        "Cuba": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Jamaica": ["Jamaica Heritage Museum", "Jamaica City Museum"],
        "Haiti": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Dominican Republic": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Puerto Rico": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Trinidad and Tobago": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Bahamas": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
    },
    "south_american_museums": {
        "Brazil": ["Christ the Redeemer", "Ipanema Beach"],
        "Argentina": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Barbados": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Chile": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Colombia": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Ecuador": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Peru": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Uruguay": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Venezuela": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Paraguay": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Bolivia": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Guyana": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
    },
    "central_american_museums": {
        "Mexico": ["Temple of the Sacred Heart", "Chichen Itza"],
        "Guatemala": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Belize": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "El Salvador": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Honduras": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
        "Nicaragua": ["Museo Nacional de Historia Natural", "Palacio de la Musica"],
    },
}

# TODO: Write a nested loop to print each country and its must-see museums in the format:
# In [country], you should visit:
# - [museum 1]
# - [museum 2]
# (Continue for each museum in the country)

for continent, countries in world_museums.items():
    for country, museums in countries.items():
        print(f"In {country}, you should visit:")
        for museum in museums:
            print(f"- {museum}")
        print()  # Add a blank line for readability